-- MySQL Script generated by MySQL Workbench
-- Thu Aug 19 10:18:47 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cash_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cash_account` (
  `cash_account_id` INT NOT NULL,
  `funds` DECIMAL(2) NOT NULL,
  `account_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cash_account_id`),
  UNIQUE INDEX `cash_account_id_UNIQUE` (`cash_account_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`investment_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`investment_account` (
  `investment_account_id` INT NOT NULL,
  `funds` DECIMAL(2) NOT NULL,
  PRIMARY KEY (`investment_account_id`),
  UNIQUE INDEX `Investment_account_id_UNIQUE` (`investment_account_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funds_transfer_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funds_transfer_account` (
  `funds_transfer_account_id` INT NOT NULL,
  `funds` DECIMAL(2) NOT NULL,
  `transfer_type` VARCHAR(45) NOT NULL,
  `investment_account_id_ft` INT NOT NULL,
  `cash_account_id_ft` INT NOT NULL,
  PRIMARY KEY (`funds_transfer_account_id`),
  UNIQUE INDEX `funds_transfer_account_id_UNIQUE` (`funds_transfer_account_id` ASC) VISIBLE,
  CONSTRAINT `cash_account_id_ft`
    FOREIGN KEY (`cash_account_id_ft`)
    REFERENCES `mydb`.`cash_account` (`cash_account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `investment_account_id_ft`
    FOREIGN KEY (`investment_account_id_ft`)
    REFERENCES `mydb`.`investment_account` (`investment_account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stocks` (
  `stock_id` INT NOT NULL,
  `time_bought` DATETIME NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `purchase_price` DECIMAL(2) NOT NULL,
  `number_of_stocks` INT NOT NULL,
  `investment_account_id_s` INT NOT NULL,
  PRIMARY KEY (`stock_id`),
  UNIQUE INDEX `stocks_id_UNIQUE` (`stock_id` ASC) VISIBLE,
  CONSTRAINT `investment_account_id_s`
    FOREIGN KEY (`investment_account_id_s`)
    REFERENCES `mydb`.`investment_account` (`investment_account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stock_transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stock_transaction` (
  `transaction_id` INT NOT NULL,
  `transaction_time` DATETIME NOT NULL,
  `amount` DECIMAL(2) NOT NULL,
  `transaction_type` VARCHAR(45) NOT NULL,
  `stock_name` VARCHAR(45) NOT NULL,
  `stock_id_tx` INT NOT NULL,
  `investment_account_id_tx` INT NOT NULL,
  PRIMARY KEY (`transaction_id`),
  UNIQUE INDEX `transaction_id_UNIQUE` (`transaction_id` ASC) VISIBLE,
  CONSTRAINT `stock_id_tx`
    FOREIGN KEY (`stock_id_tx`)
    REFERENCES `mydb`.`stocks` (`stock_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `investment_account_id_tx`
    FOREIGN KEY (`investment_account_id_tx`)
    REFERENCES `mydb`.`investment_account` (`investment_account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`etf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`etf` (
  `etf_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `purchase_price` DECIMAL(2) NOT NULL,
  `investment_account_id_etf` INT NOT NULL,
  `time_bought` DATETIME NOT NULL,
  `numeber_of_etf` INT NOT NULL,
  PRIMARY KEY (`etf_id`),
  UNIQUE INDEX `etf_id_UNIQUE` (`etf_id` ASC) VISIBLE,
  CONSTRAINT `investment_account_id_etf`
    FOREIGN KEY (`investment_account_id_etf`)
    REFERENCES `mydb`.`investment_account` (`investment_account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`futures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`futures` (
  `futures_id` INT NOT NULL,
  `expiry_date` DATETIME NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `time_bought` DATETIME NOT NULL,
  `purchase_price` DECIMAL(2) NOT NULL,
  `number_of_futures` INT NOT NULL,
  `investment_account_id_f` INT NOT NULL,
  PRIMARY KEY (`futures_id`),
  UNIQUE INDEX `futures_id_UNIQUE` (`futures_id` ASC) VISIBLE,
  CONSTRAINT `investment_account_id_f`
    FOREIGN KEY (`investment_account_id_f`)
    REFERENCES `mydb`.`investment_account` (`investment_account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
